DROP TABLE STAFF;
CREATE TABLE STAFF
(
	? NUMBER NOT NULL PRIMARY KEY,
	? VARCHAR2(? BYTE), 
	? VARCHAR2(? BYTE) NOT NULL,
	? VARCHAR2(? BYTE) NOT NULL,
);

DROP SEQUENCE STAFF_SEQ;
CREATE SEQUENCE STAFF_SEQ NOCACHE;


INSERT INTO STAFF VALUES(STAFF_SEQ.NEXTVAL, '?', '?', '?');
INSERT INTO STAFF VALUES(STAFF_SEQ.NEXTVAL, '?', '?', '?');
INSERT INTO STAFF VALUES(STAFF_SEQ.NEXTVAL, '?', '?', '?');
COMMIT;