DROP TABLE IF EXISTS FILE_ATTACH;
DROP TABLE IF EXISTS GALLERY;

CREATE TABLE GALLERY
(
    GALLERY_NO BIGINT NOT NULL AUTO_INCREMENT,  -- PK
    WRITER VARCHAR(50),
    TITLE VARCHAR(100),
    CONTENT VARCHAR(100),
    IP VARCHAR(30),
    HIT BIGINT,
    CREATE_DATE DATETIME,
    MODIFY_DATE DATETIME,
    CONSTRAINT GALLERY_PK PRIMARY KEY(GALLERY_NO)
);
CREATE TABLE FILE_ATTACH
(
    FILE_ATTACH_NO BIGINT NOT NULL AUTO_INCREMENT,  -- PK
    PATH VARCHAR(300),
    ORIGIN VARCHAR(300),
    SAVED VARCHAR(40),
    DOWNLOAD_CNT BIGINT,
    GALLERY_NO BIGINT,  -- FK
    CONSTRAINT FILE_ATTACH_PK PRIMARY KEY(FILE_ATTACH_NO),
    CONSTRAINT FILE_ATTACH_GALLERY_FK FOREIGN KEY(GALLERY_NO) REFERENCES GALLERY(GALLERY_NO) ON DELETE CASCADE
);