-- 계층형 게시판
-- 자유 게시판

DROP TABLE FREE_BOARD;
CREATE TABLE FREE_BOARD
(
    /* 글번호 */     FREE_BOARD_NO NUMBER NOT NULL PRIMARY KEY,
    /* 작성자 */     WRITER VARCHAR2(50 BYTE),
    /* 내용 */       CONTENT VARCHAR2(1000 BYTE),
    /* IP */         IP VARCHAR2(30 BYTE),
    /* 작성일 */     CREATED DATE,
    /* 삭제여부 */   STATE NUMBER,    /* 정상: 1, 삭제: -1 */
    /* 게시글/댓글*/ DEPTH NUMBER,    /* 게시글: 0, 댓글: 1 또는 1 이상 */
    /* 동일그룹*/    GROUP_NO NUMBER, /* 게시글: FREE_BORAD_NO, 댓글: 게시글의 FREE_BOARD_NO */
    /* 그룹내 순서*/ GROUP_ORD NUMBER /* 동일그룹내 표시 순서*/
);


DROP SEQUENCE FREE_BOARD_SEQ;
CREATE SEQUENCE FREE_BOARD_SEQ NOCACHE;


-- 원글
INSERT INTO FREE_BOARD VALUES (FREE_BOARD_SEQ.NEXTVAL, '작성자1', '게시글1', '0:0:0:0:0:0:0:1', SYSDATE, 1, 0, FREE_BOARD_SEQ.CURRVAL, 0);
INSERT INTO FREE_BOARD VALUES (FREE_BOARD_SEQ.NEXTVAL, '작성자2', '게시글2', '0:0:0:0:0:0:0:1', SYSDATE, 1, 0, FREE_BOARD_SEQ.CURRVAL, 0);
INSERT INTO FREE_BOARD VALUES (FREE_BOARD_SEQ.NEXTVAL, '작성자3', '게시글3', '0:0:0:0:0:0:0:1', SYSDATE, 1, 0, FREE_BOARD_SEQ.CURRVAL, 0);
INSERT INTO FREE_BOARD VALUES (FREE_BOARD_SEQ.NEXTVAL, '작성자4', '게시글4', '0:0:0:0:0:0:0:1', SYSDATE, 1, 0, FREE_BOARD_SEQ.CURRVAL, 0);
INSERT INTO FREE_BOARD VALUES (FREE_BOARD_SEQ.NEXTVAL, '작성자5', '게시글5', '0:0:0:0:0:0:0:1', SYSDATE, 1, 0, FREE_BOARD_SEQ.CURRVAL, 0);
INSERT INTO FREE_BOARD VALUES (FREE_BOARD_SEQ.NEXTVAL, '작성자6', '게시글6', '0:0:0:0:0:0:0:1', SYSDATE, 1, 0, FREE_BOARD_SEQ.CURRVAL, 0);
INSERT INTO FREE_BOARD VALUES (FREE_BOARD_SEQ.NEXTVAL, '작성자7', '게시글7', '0:0:0:0:0:0:0:1', SYSDATE, 1, 0, FREE_BOARD_SEQ.CURRVAL, 0);
INSERT INTO FREE_BOARD VALUES (FREE_BOARD_SEQ.NEXTVAL, '작성자8', '게시글8', '0:0:0:0:0:0:0:1', SYSDATE, 1, 0, FREE_BOARD_SEQ.CURRVAL, 0);
INSERT INTO FREE_BOARD VALUES (FREE_BOARD_SEQ.NEXTVAL, '작성자9', '게시글9', '0:0:0:0:0:0:0:1', SYSDATE, 1, 0, FREE_BOARD_SEQ.CURRVAL, 0);
INSERT INTO FREE_BOARD VALUES (FREE_BOARD_SEQ.NEXTVAL, '작성자10', '게시글10', '0:0:0:0:0:0:0:1', SYSDATE, 1, 0, FREE_BOARD_SEQ.CURRVAL, 0);

COMMIT;